### homePage
GET http://localhost:8030/homePage


### aboutUs
GET http://localhost:8030/aboutUs

### get Registration
GET http://localhost:8030/registration

### get Registration
POST http://localhost:8030/registration
Content-Type: application/json

{
  "login": "krowa1",
  "password": "123123",
  "password2": "123123",
  "firstName": "Michał",
  "lastName": "Kowalski",
  "city": "Kraków",
  "street": "Jasna",
  "homeNumber": "15",
  "email": "test@email.pl"
}

### registrationSuccess
GET http://localhost:8030/registration-success

### login
GET http://localhost:8030/login

### Post login
POST http://localhost:8030/login
Content-Type: application/json

{
  "login": "krowa1",
  "password": "123123"
}

### logout
GET http://localhost:8030/logout

### getSessionData
# Wartosc ciasteczka z przegladarki
GET http://localhost:8030/getSessionData
BHP_SID: 422753c439034e4d87ed44c2372d4580ef1d8c6753a92fcb544715fd7d991f22
